require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb

RSpec/ExampleLength:
  Enabled: true
  CountAsOne: ['array', 'hash']
  Max: 5

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - Gemfile
    - Rakefile
    - config.ru
    - app/mailers/application_mailer.rb
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/test.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/initializers/assets.rb
    - config/puma.rb
    - config/initializers/**/*
    - db/migrate/**/*

Style/StringLiterals:
  Exclude:
    - Gemfile
    - Rakefile
    - config.ru
    - app/mailers/application_mailer.rb
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/test.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/initializers/assets.rb
    - config/puma.rb
    - config/initializers/**/*

Style/RedundantFetchBlock:
  Exclude:
    - config/puma.rb

Style/SymbolArray:
  Exclude:
    - config/initializers/**/*

Layout/LineLength:
  Exclude:
    - config/initializers/**/*

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Rails/I18nLocaleTexts:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  CountAsOne: ['array']

Metrics/MethodLength:
  CountAsOne: ['array']
